import type { Metadata } from "next";
import { Rock_3D } from "next/font/google";
import "./globals.css";

const rock3d = Rock_3D({
  variable: "--font-rock-3d",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="icecream">
      <body
        className={`${rock3d.variable} antialiased font-[family-name:var(--font-rock-3d)]`}
      >
        {children}
      </body>
    </html>
  );
}
