import type { Metadata } from "next";
import { Bangers } from "next/font/google";
import "./globals.css";

const bangersFont = Bangers({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="icecream">
      <body className={`${bangersFont.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
