import type { Metadata } from "next";
import { Bangers, Annie_Use_Your_Telescope } from "next/font/google";
import "./globals.css";

const bangers = Bangers({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bangers",
});

const annie = Annie_Use_Your_Telescope({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-annie",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="icecream">
      <body className={`${bangers.variable} ${annie.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
